filebeat.inputs:
- type: filestream
  id: my-filestream-id
  enabled: false
  paths:
    - /var/log/*.log


filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1


setup.kibana:
  host: "localhost:5601"


output.elasticsearch:
  hosts: ["localhost:9200"]

output.logstash:
  hosts: ["localhost:5044"]



processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~


xpack.monitoring.enabled: true
http.enabled: true
http.host: 0.0.0.0
http.port: 5066

